export default {
  products: [
    {
      _id: '1',
      name: 'X-Ray 2',
      category: 'Sneakers',
      image: '/images/X-Ray-2-Square-IMEVA-SoftFoam+-Shoes.webp',
      price: 60,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: '2',
      name: 'X-Ray 4',
      category: 'Sneakers',
      image: '/images/X-Ray-2-Square-IMEVA-SoftFoam+-Shoes.webp',
      price: 80,
      brand: 'Puma',
      rating: 4.0,
      numReviews: 10,
    },
    {
      _id: '3',
      name: 'X-Ray 5',
      category: 'Sports',
      image: '/images/X-Ray-2-Square-IMEVA-SoftFoam+-Shoes.webp',
      price: 50,
      brand: 'Puma',
      rating: 4.3,
      numReviews: 10,
    },
    {
      _id: '4',
      name: 'X-Ray 7',
      category: 'Sports',
      image: '/images/X-Ray-2-Square-IMEVA-SoftFoam+-Shoes.webp',
      price: 90,
      brand: 'Puma',
      rating: 3.3,
      numReviews: 7,
    },
  ],
};
